name: unet-small-dsb2018-2

input_shape: [null, null, 1]

backbone:
  name: 'unet'
  args:
    filters: [32, 64, 128]
  weights: null

head:
  name: 'fgbg-segm'
  args: {}
  prepare_model_args: {}

training:
  callbacks:
    - 
      name: early_stopping
      args: {}
    - 
      name: reduce_lr_on_plateau
      args: {}
  batch_size: 8

data:
  name: 'stardist-dsb2018'
  train_val_split: 0.9
  normalizer: 'uint8-range'
  dataaug:
    name: 'imgaug'
    augmentors:
      - name: 'CropToFixedSize'
        args: { width: 128, height: 128 }
      - name: 'Fliplr'
        args: { p: 0.5 }
      - name: 'Flipud'
        args: { p: 0.5 }
