name: unet-small-dsb2018-2

input_shape: [null, null, 1]

backbone:
  type: 'unet'
  args:
    filters: [32, 64, 128]
  weights: null

head:
  type: 'segm'
  args:
    num_classes: 2
  prepare_model_args: {}
  prepare_data_args: {}

training:
  callbacks:
    - 
      name: early_stopping
      args: {}
    - 
      name: reduce_lr_on_plateau
      args: {}
  batch_size: 8

data:
  name: 'stardist-dsb2018'
  load_args:
    train_val_split: 0.9
    seed: 42
  seed: 12